export class Organizacion {
    IdOrganizacion?:string = '';
    IdGrupo?:string = '';    
    Moneda?:string = '';
    Nombre?:string = '';
    Direccion?:string = '';
    Telefono?:string = '';
    Email?:string = '';
    Fax?:string = '';
    Ruc?:string = '';
    Url?:string = '';
    Campo1?:string = '';
    Campo2?:string = '';
    Campo3?:string = '';
    Campo4?:string = '';
    Campo5?:string = '';
    //CodigoUsuarioCreacion:string;
    //FechaHoraCreacion:string;
    //CodigoUsuarioModificacion:string;
    //FechaHoraModificacion:string;
    Habilitado?:number = 1;
    Telefono2?:string = '';
    Telefono3?:string = '';
    AnexoTelefono?:string = '';
    AnexoTelefono2?:string = '';
    AnexoTelefono3?:string = '';
    AnexoFax?:string = '';
    CodigoPostal?:string = '';
    Representante1?:string = '';
    Representante2?:string = '';
    Representante3?:string = '';
    Representante4?:string = '';
    CargoRepresentante1?:string = '';
    CargoRepresentante2?:string = '';
    CargoRepresentante3?:string = '';
    CargoRepresentante4?:string = '';
    EmailRepresentante1?:string = '';
    EmailRepresentante2?:string = '';
    EmailRepresentante3?:string = '';
    EmailRepresentante4?:string = '';
    Provincia?:string = '';
    Ciudad?:string = '';
    Fabricante?:string = '';
    AnhoFundacion:number;
    DescripcionCia?:string = '';
    DireccionUnidadProduccion?:string = '';
    UbicacionAlmacen?:string = '';
    AlmacenTransitorioAsoc?:string = '';
    DireccionAlmacenPrincipal?:string = '';
    DireccionAlmacenTransitorio?:string = '';
    NumeroCrfq:number;
    //IdAdministrador?:string = '';
    TipoEmpresa?:string = '';
    IsoPais?:string = 'PE';
    Integrado:number;
    MonedaMig?:string = '';
    PaisMig?:string = '';
    PorAprobar:number;
    GiroNegocio?:string = '';
    NumeroEmpleados?:string = '';
    MontoVenta:number;
    CodigoEmpresaReferencia?:string = '';
    NombreEmpresaReferencial?:string = '';
    RucEmpresaReferencia?:string = '';
    CuentaPrincipal?:string = '';
    IdBanco:number;
    NombreBanco?:string = '';
    CodigoERP?:string = '';
    Estado?:string = '';
    FlagCubso:number;
    StorageAccountUrl?:string = '';
    StorageAccountApiKey?:string = '';
    CondicionContribuyente?:string = '';
    UbicacionGeo?:string = '';
    SuscriptionKey?:string = '';
    CrearCalendarios:number = 0;
    Logo?:string = 'http://md-pro-angular2.creative-tim.com/assets/img/image_placeholder.jpg';
}


